
name: Auto RT & Like X

on:
  workflow_dispatch:  # 手動実行ボタンを有効にする
  #schedule:
    #- cron: '*/15 * * * *'  # 15分ごとに自動実行

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot script
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: python main.py
